# ==========================================
# Application Configuration
# ==========================================
spring.application.name=Notification-Microservice

# ==========================================
# Server Configuration
# ==========================================
server.port=8082

# ==========================================
# NATS Configuration
# ==========================================
nats.url=nats://localhost:4222